package egzaminui.demo;

import java.util.ArrayList;

import org.springframework.util.StringUtils;
/**
 * Failas, skirtas kurti PageController failą pagal duomenų bazės, paieškos ir ataskaitos lentelių duomenis
 * 
 * @author Toma
 *
 */
public class KurtiPageControllerFaila {
	/**
	 * Sukuria LenteleBeDuomenu klasės sąrašo tipo kintamąjį duomenų bazės lentelių duomenims
	 */
	private ArrayList<LenteleBeDuomenu> lenteles;
	/**
	 * Sukuria LenteleBeDuomenu klasės sąrašo tipo kintamąjį paieškos lentelių duomenims
	 */
	private ArrayList<LenteleBeDuomenu> paieskos_lenteles;
	/**
	 * Sukuria LenteleBeDuomenu klasės sąrašo tipo kintamąjį ataskaitos lentelių duomenims
	 */
	private ArrayList<LenteleBeDuomenu> ataskaitos_lenteles;
	/**
	 * Tuščias konstruktorius
	 */
	public KurtiPageControllerFaila() {
		
	}
	/**
	 * Konstruktoriui perduodami LenteleBeDuomenu klasės sąrašo tipo duomenys, reikalingi PageController failo sudarymui
	 * @param lenteles LenteleBeDuomenu klasės sąrašo tipo kintamasis duomenų bazės lentelėms
	 * @param paieskos_lenteles LenteleBeDuomenu klasės sąrašo tipo kintamasis paieškos lentelėms
	 * @param ataskaitos_lenteles LenteleBeDuomenu klasės sąrašo tipo kintamasis ataskaitos lentelėms
	 */
	public KurtiPageControllerFaila(ArrayList<LenteleBeDuomenu> lenteles, ArrayList<LenteleBeDuomenu> paieskos_lenteles, ArrayList<LenteleBeDuomenu> ataskaitos_lenteles) {
		
		this.lenteles = lenteles;
		this.paieskos_lenteles = paieskos_lenteles;
		this.ataskaitos_lenteles = ataskaitos_lenteles;
		
	}
	/**
	 * Metodas grąžinti String sąrašo tipo kintamajį PageController failo kūrimui
	 * @return java_failui
	 */
	public ArrayList<String> javaFailui() {
		
		ArrayList<String> java_failui = new ArrayList<String>();
		String kablelis = "";
		String stulpeliu_sarasas = "";
		
		java_failui.add("package egzaminui.demo;");
		java_failui.add("");
		java_failui.add("import org.hibernate.Session;");
		java_failui.add("import org.hibernate.SessionFactory;");
		java_failui.add("import org.springframework.beans.factory.annotation.Autowired;");
		java_failui.add("import org.springframework.stereotype.Controller;");
		java_failui.add("import org.springframework.ui.Model;");
		java_failui.add("import org.springframework.web.bind.annotation.RequestMapping;");
		java_failui.add("import org.springframework.web.bind.annotation.RequestMethod;");
		java_failui.add("import org.springframework.web.bind.annotation.RequestParam;");
		java_failui.add("");
		java_failui.add("import com.google.gson.Gson;");
		java_failui.add("");
		java_failui.add("import java.util.ArrayList;");
		java_failui.add("import java.util.List;");
		java_failui.add("import java.util.Optional;");
		java_failui.add("import javax.persistence.EntityManagerFactory;");
		java_failui.add("");
		java_failui.add("@Controller");
		java_failui.add("public class PageController {");
		for( int i=0; i < lenteles.size(); i++ ) {
			
			java_failui.add("	/**");
			java_failui.add("	* Sukuria " + lenteles.get(i).getLenteles_pav() + "_rep " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "Repository klasės tipo kintamąjį");
			java_failui.add("	*/");
			java_failui.add("	@Autowired // This means to get the bean called userRepository");
			java_failui.add("    // Which is auto-generated by Spring, we will use it to handle the data");
			java_failui.add("	private " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "Repository " + lenteles.get(i).getLenteles_pav() + "_rep;");
		}
		java_failui.add("	@Autowired ");
		java_failui.add("	EntityManagerFactory factory;");
		java_failui.add("	/**");
		java_failui.add("	* Metodas grąžinti SessionFactory klasės kintamajį kreipimuisi į duombazę");
		java_failui.add("	* @return factory.unwrap(SessionFactory.class);");
		java_failui.add("	*/");
		java_failui.add("	// @Bean");
		java_failui.add("	public SessionFactory sessionFactory() {");
		java_failui.add("		");
		java_failui.add("	        if (factory.unwrap(SessionFactory.class) == null) {");
		java_failui.add("	            throw new NullPointerException(\"factory is not a hibernate factory\");");
		java_failui.add("	        }");
		java_failui.add("	        return factory.unwrap(SessionFactory.class);");
		java_failui.add("	}");
		java_failui.add("	");
		java_failui.add("	/**");
		java_failui.add("	* Metodas grąžinti String tipo kintamajį html adresui");
		java_failui.add("	* @param model Model klasės kintamasis");
		java_failui.add("	* @return index");
		java_failui.add("	*/");
		java_failui.add("	@RequestMapping(path=\"/\", method={ RequestMethod.GET, RequestMethod.POST })");
		java_failui.add("	public String index(Model model) {");
		java_failui.add("		model.addAttribute(\"lst_menu\", Menu.values() );");
		java_failui.add("		return \"index\";");
		java_failui.add("	}");
		java_failui.add("	");
		for( int i=0; i < paieskos_lenteles.size(); i++ ) {
			java_failui.add("	/**");
			java_failui.add("	* Metodas grąžinti String tipo kintamajį html adresui");
			for( int y=0; y < paieskos_lenteles.get(i).getKiekis_stulpeliu(); y++ ) {
				java_failui.add("	* @param " + paieskos_lenteles.get(i).getStulpeliu_pav().get(y) + " " + StringUtils.capitalize(paieskos_lenteles.get(i).getStulpeliu_tipai().get(y)) + " klasės tipo kintamasis");
			}
			java_failui.add("	* @param veiksmas String klasės kintamasis");
			java_failui.add("	* @param model Model klasės kintamasis");
			java_failui.add("	* @return " + paieskos_lenteles.get(i).getLenteles_pav());
			java_failui.add("	*/");
			java_failui.add("	@RequestMapping(path=\"" + (char)47 + paieskos_lenteles.get(i).getLenteles_pav() + "\", method={ RequestMethod.GET, RequestMethod.POST })");
			java_failui.add("    public String " + paieskos_lenteles.get(i).getLenteles_pav() + "(");
			kablelis = "";
			for( int y=0; y < paieskos_lenteles.get(i).getKiekis_stulpeliu(); y++ ) {
	
				java_failui.add("    		" + kablelis + " @RequestParam(name=\"" + paieskos_lenteles.get(i).getStulpeliu_pav().get(y) + "\", required=false, defaultValue=\"\") " + paieskos_lenteles.get(i).getStulpeliu_tipai().get(y) + " " + paieskos_lenteles.get(i).getStulpeliu_pav().get(y));
				stulpeliu_sarasas += kablelis + " " + paieskos_lenteles.get(i).getStulpeliu_pav().get(y);
				kablelis = ",";
			}
			java_failui.add("    		, @RequestParam(name=\"veiksmas\", required=false, defaultValue=\"neieskoti\") String veiksmas");
			java_failui.add("    		, Model model ");
			java_failui.add("    	) {");
			java_failui.add("        ");
			java_failui.add("		BackEndMessage back_end_message = new BackEndMessage ( \"nieko dar neveikem\", false, \"pranesimas_grey\" );");
			java_failui.add("		");
			java_failui.add("        if ( veiksmas.equals(\"ieskoti\") ) {");
			java_failui.add("        	");
			java_failui.add("			Session session = this.sessionFactory().openSession();");
			java_failui.add("        	");
			java_failui.add("        	" + StringUtils.capitalize(this.paieskos_lenteles.get(i).getLenteles_pav()) + " sql_uzklausa =  new " + StringUtils.capitalize(this.paieskos_lenteles.get(i).getLenteles_pav()) + " ( session );");
			java_failui.add("			model.addAttribute( \"sql_ataskaitai\", sql_uzklausa.ataskaitosLentele(" + stulpeliu_sarasas + " ));");
			java_failui.add("        ");
			java_failui.add("        	} else {");
			java_failui.add("        		");
			java_failui.add("    			model.addAttribute( \"sql_ataskaitai\", new ArrayList<" + StringUtils.capitalize(this.ataskaitos_lenteles.get(i).getLenteles_pav()) + ">() );");
			java_failui.add("        	}");
			java_failui.add("        	");
			java_failui.add("        model.addAttribute( \"back_end_message\", back_end_message );");
			java_failui.add("        model.addAttribute( \"lst_menu\", Menu.values() ); ");
			java_failui.add("        //model.addAttribute( \"lst\", " + lenteles.get(0).getLenteles_pav() + "_rep.findAll() );");
			java_failui.add("        ");
			java_failui.add("        return \"" + paieskos_lenteles.get(i).getLenteles_pav() + "\";");
			java_failui.add("    }");
			java_failui.add("	");	
		}
		for( int i=0; i < lenteles.size(); i++ ) {
			
			kablelis = "";
			java_failui.add("	/**");
			java_failui.add("	* Metodas grąžinti String tipo kintamajį html adresui");
			for( int y=0; y < lenteles.get(i).getKiekis_stulpeliu(); y++ ) {
				java_failui.add("	* @param " + lenteles.get(i).getStulpeliu_pav().get(y) + " " + StringUtils.capitalize(lenteles.get(i).getStulpeliu_tipai().get(y)) + " klasės tipo kintamasis");
			}
			java_failui.add("	* @param veiksmas String klasės kintamasis");
			java_failui.add("	* @param salinti String klasės kintamasis");
			java_failui.add("	* @param model Model klasės kintamasis");
			java_failui.add("	* @return " + lenteles.get(i).getLenteles_pav());
			java_failui.add("	*/");
			java_failui.add("	@RequestMapping(path=\"" + (char)47 + lenteles.get(i).getLenteles_pav() + "\", method={ RequestMethod.GET, RequestMethod.POST })");
			java_failui.add("    public String " + lenteles.get(i).getLenteles_pav() + "(");
			for(int y=0; y < (lenteles.get(i).getKiekis_stulpeliu()); y++) {
				
				java_failui.add("    		" + kablelis + " @RequestParam(name=\"" + lenteles.get(i).getStulpeliu_pav().get(y) + "\", required=false, defaultValue=\"\") " + lenteles.get(i).getStulpeliu_tipai().get(y) + " " + lenteles.get(i).getStulpeliu_pav().get(y));
				kablelis = ",";
			}
			java_failui.add("    		, @RequestParam(name=\"veiksmas\", required=false, defaultValue=\"neveikti\") String veiksmas");
			java_failui.add("    		, @RequestParam(name=\"salinti\", required=false, defaultValue=\"nesalinti\") String salinti");
			java_failui.add("    		, Model model ");
			java_failui.add("    	) {");
			java_failui.add("        ");
			java_failui.add("		BackEndMessage back_end_message = new BackEndMessage ( \"nieko dar neveikem\", false, \"pranesimas_grey\" );");
			java_failui.add("		");
			java_failui.add("        if ( veiksmas.equals(\"papildyti\") ) {");
			java_failui.add("        	");
			java_failui.add("        	/*List <" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "> lst_" + lenteles.get(i).getLenteles_pav() + " = " + lenteles.get(i).getLenteles_pav() + "_rep.findBy" + StringUtils.capitalize(lenteles.get(i).getStulpeliu_pav().get(1)) + "( " + lenteles.get(i).getStulpeliu_pav().get(1) + " );");
			java_failui.add("        	");
			java_failui.add("        	if ( lst_" + lenteles.get(i).getLenteles_pav() + ".size() > 0 ) {");
			java_failui.add("        		");
			java_failui.add("        		back_end_message.setMessage( \"produktas su tokiu pav '\" + " + lenteles.get(i).getStulpeliu_pav().get(1) + " + \"' jau egzistuoja\" );");
			java_failui.add("        		back_end_message.setCss_class( \"pranesimas_red\" );");
			java_failui.add("        		");
			java_failui.add("        	} else {*/");
			java_failui.add("        		");
			stulpeliu_sarasas = "";
			kablelis = "";
			for(int y=0; y < lenteles.get(i).getKiekis_stulpeliu(); y++) {
				
				stulpeliu_sarasas += kablelis + " " + lenteles.get(i).getStulpeliu_pav().get(y);
				kablelis = ",";
			}
			java_failui.add("	        	" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + " " + lenteles.get(i).getLenteles_pav() + " = new " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "(" + stulpeliu_sarasas + " );");
			java_failui.add("	        	" + lenteles.get(i).getLenteles_pav() + "_rep.save( " + lenteles.get(i).getLenteles_pav() + " );");
			java_failui.add("        		back_end_message.setMessage( \"į sąrašą įtrauktas '\" + " + lenteles.get(i).getStulpeliu_pav().get(1) + " + \"'\" );");
			java_failui.add("        		back_end_message.setCss_class( \"pranesimas_green\" );");
			java_failui.add("        		");
			java_failui.add("        	//}");
			java_failui.add("        }");
			java_failui.add("        ");
			java_failui.add("        if ( veiksmas.equals(\"pakeisti\") ) {");
			java_failui.add("        	");
			java_failui.add("        	" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + " " + lenteles.get(i).getLenteles_pav() + " = new " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "();");
			java_failui.add("        	Optional <" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "> found = " + lenteles.get(i).getLenteles_pav() + "_rep.findById( id );");
			java_failui.add("        	");
			java_failui.add("        	if ( found.isPresent() ) {");
			java_failui.add("    			");
			java_failui.add("        		" + lenteles.get(i).getLenteles_pav() + " = found.get();");
			for(int y=0; y < lenteles.get(i).getKiekis_stulpeliu(); y++) {
				
				java_failui.add("        		" + lenteles.get(i).getLenteles_pav() + ".set" + StringUtils.capitalize(lenteles.get(i).getStulpeliu_pav().get(y)) + "( " + lenteles.get(i).getStulpeliu_pav().get(y) + " );");
			}
			java_failui.add("	        	" + lenteles.get(i).getLenteles_pav() + "_rep.save( " + lenteles.get(i).getLenteles_pav() + " );");
			java_failui.add("        	}");
			java_failui.add("");
			java_failui.add("        }");
			java_failui.add("        if ( salinti.equals(\"pasalinti\") ) {");
			java_failui.add("        	");
			java_failui.add("        	Optional <" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "> found = " + lenteles.get(i).getLenteles_pav() + "_rep.findById( id );");
			java_failui.add("        	");
			java_failui.add("        	if ( found.isPresent() ) {");
			java_failui.add("    			");
			java_failui.add("        		" + lenteles.get(i).getLenteles_pav() + "_rep.deleteById( id );");
			java_failui.add(" 		");
			java_failui.add(" 			}");
			java_failui.add("        }");
			java_failui.add("        model.addAttribute( \"back_end_message\", back_end_message );");
			java_failui.add("        model.addAttribute( \"lst_menu\", Menu.values() ); ");
			java_failui.add("        model.addAttribute( \"lst\", " + lenteles.get(i).getLenteles_pav() + "_rep.findAll() );");
			java_failui.add("        ");
			java_failui.add("        return \"" + lenteles.get(i).getLenteles_pav() + "\";");
			java_failui.add("    }");
			java_failui.add("	");
		}
		java_failui.add("}");
		return java_failui;
	}
}

