package egzaminui.demo;
import java.util.ArrayList;
import org.springframework.util.StringUtils;

public class KurtiPageControllerFaila {
	
	private ArrayList<LenteleSuDuomenimis> lenteles;
	private LenteleBeDuomenu lentele;
	
	public KurtiPageControllerFaila() {
		
	}
	
	public KurtiPageControllerFaila(ArrayList<LenteleSuDuomenimis> lenteles, LenteleBeDuomenu ataskaitos_lentele) {
		
		this.lenteles = lenteles;
		this.lentele = ataskaitos_lentele;
		
	}
	public ArrayList<String> JavaFailui() {
		ArrayList<String> JavaFailui = new ArrayList<String>();
		JavaFailui.add("package egzaminui.demo;");
		JavaFailui.add("");
		JavaFailui.add("import org.hibernate.Session;");
		JavaFailui.add("import org.hibernate.SessionFactory;");
		JavaFailui.add("import org.springframework.beans.factory.annotation.Autowired;");
		JavaFailui.add("import org.springframework.stereotype.Controller;");
		JavaFailui.add("import org.springframework.ui.Model;");
		JavaFailui.add("import org.springframework.web.bind.annotation.RequestMapping;");
		JavaFailui.add("import org.springframework.web.bind.annotation.RequestMethod;");
		JavaFailui.add("import org.springframework.web.bind.annotation.RequestParam;");
		JavaFailui.add("");
		JavaFailui.add("import com.google.gson.Gson;");
		JavaFailui.add("");
		JavaFailui.add("import java.util.ArrayList;");
		JavaFailui.add("import java.util.List;");
		JavaFailui.add("import java.util.Optional;");
		JavaFailui.add("import javax.persistence.EntityManagerFactory;");
		JavaFailui.add("");
		JavaFailui.add("@Controller");
		JavaFailui.add("public class PageController {");
		for( int i=0; i < lenteles.size(); i++ ) {
			JavaFailui.add("	@Autowired // This means to get the bean called userRepository");
			JavaFailui.add("    // Which is auto-generated by Spring, we will use it to handle the data");
			JavaFailui.add("	private " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "Repository " + lenteles.get(i).getLenteles_pav() + "_rep;");
		}
		JavaFailui.add("	@Autowired ");
		JavaFailui.add("	EntityManagerFactory factory;");
		JavaFailui.add("");
		JavaFailui.add("	// @Bean");
		JavaFailui.add("	public SessionFactory sessionFactory() {");
		JavaFailui.add("		");
		JavaFailui.add("	        if (factory.unwrap(SessionFactory.class) == null) {");
		JavaFailui.add("	            throw new NullPointerException(\"factory is not a hibernate factory\");");
		JavaFailui.add("	        }");
		JavaFailui.add("	        return factory.unwrap(SessionFactory.class);");
		JavaFailui.add("	}");
		JavaFailui.add("	");
		String kablelis = "";
		JavaFailui.add("	@RequestMapping(path=\"/\", method={ RequestMethod.GET, RequestMethod.POST })");
		JavaFailui.add("	public String index(Model model) {");
		JavaFailui.add("		model.addAttribute(\"lst_menu\", Menu.values() );");
		JavaFailui.add("		return \"index\";");
		JavaFailui.add("	}");
		JavaFailui.add("	");
		JavaFailui.add("	@RequestMapping(path=\"" + (char)47 + this.lentele.getLenteles_pav() + "\", method={ RequestMethod.GET, RequestMethod.POST })");
		JavaFailui.add("    public String " + this.lentele.getLenteles_pav() + "(");
		String stulpeliu_sarasas = "";
		kablelis = "";
		for( int i=0; i < this.lentele.getKiekis_stulpeliu(); i++ ) {

			JavaFailui.add("    		" + kablelis + " @RequestParam(name=\"" + this.lentele.getStulpeliu_pav().get(i) + "\", required=false, defaultValue=\"\") " + this.lentele.getStulpeliu_tipai().get(i) + " " + this.lentele.getStulpeliu_pav().get(i));
			stulpeliu_sarasas += kablelis + " " + this.lentele.getStulpeliu_pav().get(i);
			kablelis = ",";
		}
		JavaFailui.add("    		, @RequestParam(name=\"veiksmas\", required=false, defaultValue=\"neieskoti\") String veiksmas");
		JavaFailui.add("    		, Model model ");
		JavaFailui.add("    	) {");
		JavaFailui.add("        ");
		JavaFailui.add("		BackEndMessage back_end_message = new BackEndMessage ( \"nieko dar neveikem\", false, \"pranesimas_grey\" );");
		JavaFailui.add("		");
		JavaFailui.add("        if ( veiksmas.equals(\"ieskoti\") ) {");
		JavaFailui.add("        	");
		JavaFailui.add("			Session session = this.sessionFactory().openSession();");
		JavaFailui.add("        	");
		JavaFailui.add("        	KurtiSqlUzklausai sql_uzklausa =  new KurtiSqlUzklausai ( session );");
		JavaFailui.add("			model.addAttribute( \"sql_ataskaitai\", sql_uzklausa.paieskosLentele(" + stulpeliu_sarasas + " ));");
		JavaFailui.add("        ");
		JavaFailui.add("        	} else {");
		JavaFailui.add("        		");
		JavaFailui.add("    			model.addAttribute( \"sql_ataskaitai\", new ArrayList<PaieskosLentele>() );");
		JavaFailui.add("        	}");
		JavaFailui.add("        	");
		JavaFailui.add("        model.addAttribute( \"back_end_message\", back_end_message );");
		JavaFailui.add("        model.addAttribute( \"lst_menu\", Menu.values() ); ");
		JavaFailui.add("        //model.addAttribute( \"lst\", " + lenteles.get(0).getLenteles_pav() + "_rep.findAll() );");
		JavaFailui.add("        ");
		JavaFailui.add("        return \"" + this.lentele.getLenteles_pav() + "\";");
		JavaFailui.add("    }");
		JavaFailui.add("	");	
		for( int i=0; i < lenteles.size(); i++ ) {
			kablelis = "";
			JavaFailui.add("	@RequestMapping(path=\"" + (char)47 + lenteles.get(i).getLenteles_pav() + "\", method={ RequestMethod.GET, RequestMethod.POST })");
			JavaFailui.add("    public String " + lenteles.get(i).getLenteles_pav() + "(");
			for(int y=0; y < (lenteles.get(i).getKiekis_stulpeliu()); y++) {
				JavaFailui.add("    		" + kablelis + " @RequestParam(name=\"" + lenteles.get(i).getStulpeliu_pav().get(y) + "\", required=false, defaultValue=\"\") " + lenteles.get(i).getStulpeliu_tipai().get(y) + " " + lenteles.get(i).getStulpeliu_pav().get(y));
				kablelis = ",";
			}
			
			JavaFailui.add("    		, @RequestParam(name=\"veiksmas\", required=false, defaultValue=\"neveikti\") String veiksmas");
			JavaFailui.add("    		, @RequestParam(name=\"salinti\", required=false, defaultValue=\"nesalinti\") String salinti");
			JavaFailui.add("    		, Model model ");
			JavaFailui.add("    	) {");
			JavaFailui.add("        ");
			JavaFailui.add("		BackEndMessage back_end_message = new BackEndMessage ( \"nieko dar neveikem\", false, \"pranesimas_grey\" );");
			JavaFailui.add("		");
			JavaFailui.add("        if ( veiksmas.equals(\"papildyti\") ) {");
			JavaFailui.add("        	");
			JavaFailui.add("        	/*List <" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "> lst_" + lenteles.get(i).getLenteles_pav() + " = " + lenteles.get(i).getLenteles_pav() + "_rep.findBy" + StringUtils.capitalize(lenteles.get(i).getStulpeliu_pav().get(1)) + "( " + lenteles.get(i).getStulpeliu_pav().get(1) + " );");
			JavaFailui.add("        	");
			JavaFailui.add("        	if ( lst_" + lenteles.get(i).getLenteles_pav() + ".size() > 0 ) {");
			JavaFailui.add("        		");
			JavaFailui.add("        		back_end_message.setMessage( \"produktas su tokiu pav '\" + " + lenteles.get(i).getStulpeliu_pav().get(1) + " + \"' jau egzistuoja\" );");
			JavaFailui.add("        		back_end_message.setCss_class( \"pranesimas_red\" );");
			JavaFailui.add("        		");
			JavaFailui.add("        	} else {*/");
			JavaFailui.add("        		");
			stulpeliu_sarasas = "";
			kablelis = "";
			for(int y=0; y < lenteles.get(i).getKiekis_stulpeliu(); y++) {
				stulpeliu_sarasas += kablelis + " " + lenteles.get(i).getStulpeliu_pav().get(y);
				kablelis = ",";
			}
			JavaFailui.add("	        	" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + " " + lenteles.get(i).getLenteles_pav() + " = new " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "(" + stulpeliu_sarasas + " );");
			JavaFailui.add("	        	" + lenteles.get(i).getLenteles_pav() + "_rep.save( " + lenteles.get(i).getLenteles_pav() + " );");
			JavaFailui.add("        		back_end_message.setMessage( \"į sąrašą įtrauktas '\" + " + lenteles.get(i).getStulpeliu_pav().get(1) + " + \"'\" );");
			JavaFailui.add("        		back_end_message.setCss_class( \"pranesimas_green\" );");
			JavaFailui.add("        		");
			JavaFailui.add("        	//}");
			JavaFailui.add("        }");
			JavaFailui.add("        ");
			JavaFailui.add("        if ( veiksmas.equals(\"pakeisti\") ) {");
			JavaFailui.add("        	");
			JavaFailui.add("        	" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + " " + lenteles.get(i).getLenteles_pav() + " = new " + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "();");
			JavaFailui.add("        	Optional <" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "> found = " + lenteles.get(i).getLenteles_pav() + "_rep.findById( id );");
			JavaFailui.add("        	");
			JavaFailui.add("        	if ( found.isPresent() ) {");
			JavaFailui.add("    			");
			JavaFailui.add("        		" + lenteles.get(i).getLenteles_pav() + " = found.get();");
			for(int y=0; y < lenteles.get(i).getKiekis_stulpeliu(); y++) {
				JavaFailui.add("        		" + lenteles.get(i).getLenteles_pav() + ".set" + StringUtils.capitalize(lenteles.get(i).getStulpeliu_pav().get(y)) + "( " + lenteles.get(i).getStulpeliu_pav().get(y) + " );");
			}

			JavaFailui.add("	        	" + lenteles.get(i).getLenteles_pav() + "_rep.save( " + lenteles.get(i).getLenteles_pav() + " );");
			JavaFailui.add("        	}");
			JavaFailui.add("");
			JavaFailui.add("        }");
			JavaFailui.add("        if ( salinti.equals(\"pasalinti\") ) {");
			JavaFailui.add("        	");
			JavaFailui.add("        	Optional <" + StringUtils.capitalize(lenteles.get(i).getLenteles_pav()) + "> found = " + lenteles.get(i).getLenteles_pav() + "_rep.findById( id );");
			JavaFailui.add("        	");
			JavaFailui.add("        	if ( found.isPresent() ) {");
			JavaFailui.add("    			");
			JavaFailui.add("        		" + lenteles.get(i).getLenteles_pav() + "_rep.deleteById( id );");
			JavaFailui.add(" 		");
			JavaFailui.add(" 			}");
			JavaFailui.add("        }");
			JavaFailui.add("        model.addAttribute( \"back_end_message\", back_end_message );");
			JavaFailui.add("        model.addAttribute( \"lst_menu\", Menu.values() ); ");
			JavaFailui.add("        model.addAttribute( \"lst\", " + lenteles.get(i).getLenteles_pav() + "_rep.findAll() );");
			JavaFailui.add("        ");
			JavaFailui.add("        return \"" + lenteles.get(i).getLenteles_pav() + "\";");
			JavaFailui.add("    }");
			JavaFailui.add("	");
		}
		JavaFailui.add("}");
		return JavaFailui;
	}
}

